export const SEARCH_CITY = 'SEARCH_CITY';
export const GET_WEATHER = 'GET_WEATHER';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const CLEAR_USER_LOCATION = 'CLEAR_USER_LOCATION';
export const SET_IS_LOADING = 'SET_IS_LOADING';